# Generated by Django 5.1.5 on 2025-01-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircare_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairprofile',
            name='brittleness',
            field=models.CharField(choices=[('none', 'None'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hairprofile',
            name='hair_length',
            field=models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hairprofile',
            name='hair_type',
            field=models.CharField(choices=[('straight', 'Straight'), ('wavy', 'Wavy'), ('curly', 'Curly'), ('coily', 'Coily')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hairprofile',
            name='porosity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50),
        ),
    ]
