# Generated by Django 5.1.5 on 2025-05-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircare_app', '0002_alter_hairprofile_brittleness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('hair_type', models.CharField(choices=[('straight', 'Пряме'), ('wavy', 'Хвилясте'), ('curly', 'Кучеряве'), ('coily', 'Кучеряво-закручене')], max_length=50)),
                ('category', models.CharField(choices=[('daily', 'Щоденні'), ('weekly', 'Щотижневі'), ('longterm', 'Довгострокові')], max_length=20)),
            ],
        ),
    ]
