# Generated by Django 5.1.5 on 2025-05-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haircare_app', '0003_recommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
